apiVersion: v1
kind: Service
metadata:
  name: reporting-service
  namespace: warranty-hub
  labels:
    app: reporting-service
spec:
  type: ClusterIP
  selector:
    app: reporting-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000